title: "My GitHub Pages Site"
email: "your-email@example.com"
description: "A brief description of your site"
url: "https://yourusername.github.io"
baseurl: ""  # サブディレクトリに配置する場合は、そのパスを設定
theme: "minima"  # GitHub Pagesのデフォルトテーマ
